version: 1.0.0.{build}

image: Visual Studio 2017

configuration: Release

init:
- ps: $Env:VersionSuffixParam = "--version-suffix"
- ps: $Env:VersionSuffixValue = ("ci-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))

install:  
# .NET Core SDK binaries
- ps: $urlCurrent = "https://download.microsoft.com/download/3/7/F/37F1CA21-E5EE-4309-9714-E914703ED05A/dotnet-dev-win-x64.2.0.0-preview1-005977.exe"
- ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
- ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
- ps: $tempFileCurrent = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), [System.IO.Path]::GetRandomFileName())
- ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
- ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
- ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

before_build:
- ps: dotnet --info
- ps: dotnet restore -v Minimal

build_script:
- ps: dotnet build -c $Env:CONFIGURATION $Env:VersionSuffixParam $Env:VersionSuffixValue
- ps: dotnet pack src\R4Mvc.Tools -c $Env:CONFIGURATION $Env:VersionSuffixParam $Env:VersionSuffixValue

artifacts:
- path: '**\*.nupkg'

for:
- branches:
    only:
    - develop

  deploy:
    provider: NuGet
    server: https://www.myget.org/F/r4mvc/api/v2/package
    symbol_server: https://www.myget.org/F/r4mvc/symbols/api/v2/package
    api_key:
      secure: DdgwyUm4/aaCfk28jRGRFgQpqcCp6OvuqCZLZaHjNAPHZuia0+PF01zC8JGpWfe7
    artifact: /.*\.nupkg/

- branches:
    only:
    - /feature\/.*/

  init:
  - ps: $Env:VersionSuffixValue = ("ci-" + $Env:APPVEYOR_REPO_BRANCH.Substring(8) + "-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))

  deploy:
    provider: NuGet
    server: https://www.myget.org/F/r4mvc/api/v2/package
    symbol_server: https://www.myget.org/F/r4mvc/symbols/api/v2/package
    api_key:
      secure: DdgwyUm4/aaCfk28jRGRFgQpqcCp6OvuqCZLZaHjNAPHZuia0+PF01zC8JGpWfe7
    artifact: /.*\.nupkg/

- branches:
    only:
    - /prerelease\/.*/

  init:
  - ps: $Env:VersionSuffixValue = ($Env:APPVEYOR_REPO_BRANCH.Substring(11) + "-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))

  deploy:
    provider: NuGet
    api_key:
      secure: oK/7qSZDyR1umPtWP8zAswwPfIE0FJPeEkkQQMRKj6e6eq0tdEIwbPh37lGBDeSi
    artifact: /.*\.nupkg/

- branches:
    only:
    - master

  init:
  - ps: $Env:VersionSuffixParam = $null
  - ps: $Env:VersionSuffixValue = $null

  deploy:
    provider: NuGet
    api_key:
      secure: oK/7qSZDyR1umPtWP8zAswwPfIE0FJPeEkkQQMRKj6e6eq0tdEIwbPh37lGBDeSi
    artifact: /.*\.nupkg/
